project/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('cms.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

conference/models.py
from django.db import models
from django.contrib.sites.models import Site
from django.contrib.sites.managers import CurrentSiteManager


class Speaker(models.Model):
    picture = models.ImageField(
        upload_to=u'speakers/',
        blank=True,
        null=True
    )
    name = models.CharField(
        max_length=100
    )
    reference = models.CharField(
        max_length=100
    )
    about = models.TextField(
        max_length=200,
        blank=True,
        null=True
    )
    facebook = models.URLField(
        blank=True,
        null=True
    )
    twitter = models.URLField(
        blank=True,
        null=True
    )
    googleplus = models.URLField(
        blank=True,
        null=True
    )
    homepage = models.URLField(
        blank=True,
        null=True
    )
    sites = models.ManyToManyField(Site)

    objects = models.Manager()
    on_site = CurrentSiteManager()

    def __unicode__(self):
        return self.name

    def schedules(self):
        return Schedule.on_site.filter(speaker=self).order_by('start_at')


class Schedule(models.Model):
    start_at = models.TimeField()
    title = models.CharField(
        max_length=100
    )
    about = models.TextField(
        max_length=200,
        blank=True,
        null=True
    )
    speaker = models.ForeignKey(Speaker)
    site = models.ForeignKey(Site)

    objects = models.Manager()
    on_site = CurrentSiteManager()

    def __unicode__(self):
        return self.title

QUOTE_CHOICES = (
    ('diamond', 'Diamond'),
    ('platinum', 'Platinum'),
    ('gold', 'Gold'),
    ('support', 'Support'),
)


class Partner(models.Model):
    sm_image = models.ImageField(
        upload_to='partners/lower/',
        help_text=u'High resolution with 110x35.'
    )
    lg_image = models.ImageField(
        upload_to='partners/higher/',
        help_text=u'High resolution with 320x160.'
    )
    name = models.CharField(
        max_length=100
    )
    homepage = models.URLField(
        blank=True,
        null=True
    )
    about = models.TextField(
        max_length=200,
        blank=True,
        null=True
    )
    quote = models.CharField(
        max_length=25,
        default='gold',
        choices=QUOTE_CHOICES
    )
    site = models.ForeignKey(Site)

    on_site = CurrentSiteManager()

    def __unicode__(self):
        return self.name


CITY_CHOICES = (
    ('bh', 'Belo Horizonte'),
)


class Conference(models.Model):
    realization_at = models.DateField(
        blank=True,
        null=True
    )
    address = models.CharField(
        max_length=180,
        blank=True,
        null=True
    )
    city = models.CharField(
        max_length=2,
        choices=CITY_CHOICES,
        default='bh'
    )
    latitude = models.CharField(
        max_length=30,
        blank=True,
        null=True
    )
    longitude = models.CharField(
        max_length=30,
        blank=True,
        null=True
    )

    site = models.OneToOneField(Site)

    def __unicode__(self):
        return self.site.name

core/models.py
from django.db import models

from cms.models.pluginmodel import CMSPlugin


class PageContent(CMSPlugin):
    background = models.BooleanField(
        default=False
    )
    identify = models.CharField(
        max_length=100
    )
    published = models.BooleanField(
        default=False
    )

    def __unicode__(self):
        return self.identify


class Anchor(CMSPlugin):
    name = models.CharField(
        max_length=80
    )
    identify = models.CharField(
        max_length=100
    )

    def __unicode__(self):
        return self.name


class SlideShow(CMSPlugin):
    name = models.CharField(
        max_length=100
    )

    def __unicode__(self):
        return self.name

    def copy_relations(self, oldinstance):
        for associated_item in oldinstance.slide_set.all():
            associated_item.pk = None
            associated_item.plugin = self
            associated_item.save()


class Slide(models.Model):
    title = models.CharField(
        max_length=100
    )
    image = models.ImageField(
        upload_to='slides/'
    )
    plugin = models.ForeignKey(SlideShow)

    def __unicode__(self):
        return self.title


class About(CMSPlugin):
    body = models.TextField()
    media = models.TextField(
        blank=True,
        null=True,
        help_text=u'Media to publicize the event'
    )

    def __unicode__(self):
        return 'About <{}>'.format(self.pk)

conference/views.py
from django.shortcuts import render

# Create your views here.

core/views.py
from django.shortcuts import render

# Create your views here.

conference/templates/plugins/conference/partners.html
{% load thumbnail %}
<div class="logos">
  {% for partner in partners_list %}
  <div class="logo"><a href="{{ partner.homepage }}"><img src="{{ partner.sm_image.url }}" alt="{{ partner.name }}"></a></div>
  {% endfor %}
  <div class="quote-support">
    <h4>Apoio</h4>
    {% for partner in support_list %}
    {% thumbnail partner.sm_image "x90" as im %}
    <div class="logo"><a href="{{ partner.homepage }}"><img src="{{ partner.sm_image.url }}" alt="{{ partner.name }}" style="height:90px;"></a></div>
    {% endthumbnail %}
    {% endfor %}
  </div>
</div>

conference/templates/plugins/conference/schedule.html
<ul class="nav nav-tabs" role="tablist">
  <li class="active"><a href="#first-day" role="tab" data-toggle="tab">{{ conference.realization_date }}</a></li>
  <!-- <li><a href="#september-27" role="tab" data-toggle="tab">Tuesday, September 27</a></li> -->
</ul>
<!-- Tab panes -->
<div class="tab-content">
  <div class="tab-pane fade in active" id="first-day">
    <div class="panel-group" id="schedule-table-first-day">
      {% for schedule in schedule_list %}
      <div class="panel panel-default">
        <a href="#first-day-{{ forloop.counter }}" class="panel-header" data-toggle="collapse" data-parent="#schedule-table-first-day">
          <div class="row">
            <div class="col-md-2 col-sm-2">
              <div class="time">
                <i class="fa fa-clock-o"></i>
                <figure>{{ schedule.start_at }}</figure>
              </div>
            </div>
            <div class="col-md-10 col-sm-10">
              <div class="title"><h3>{{ schedule.title }}</h3></div>
            </div>
          </div>
          <i class="fa fa-plus"></i>
        </a><!-- .panel-header -->
        <div id="first-day-1" class="panel-collapse collapse description">
          <div class="row">
            <div class="col-md-10 col-md-offset-2 col-sm-10 col-sm-offset-2">
              <div class="panel-body">
                {{ schedule.about|linebreaks }}
              </div>
            </div>
          </div>
        </div><!-- .panel-collapse -->
      </div><!-- .panel -->
      {% endfor %}
      <!-- <div class="panel panel-default">
        <a href="#first-day-2" class="panel-header" data-toggle="collapse" data-parent="#schedule-table-first-day">
          <div class="row">
            <div class="col-md-2 col-sm-2">
              <div class="time">
                <i class="fa fa-clock-o"></i>
                <figure>09:30</figure>
              </div>
            </div>
            <div class="col-md-10 col-sm-10">
              <div class="title"><h3>Aenean suscipit euismod nisl, eget vehicula est bibendum et</h3></div>
            </div>
          </div>
          <i class="fa fa-plus"></i>
        </a>.panel-header
        <div id="first-day-2" class="panel-collapse collapse description">
          <div class="row">
            <div class="col-md-10 col-md-offset-2 col-sm-10 col-sm-offset-2">
              <div class="panel-body">
                <p>Praesent quis sem sed est feugiat tincidunt ut sit amet augue. Sed ac libero iaculis, laoreet enim nec, pretium ante. Donec facilisis, turpis eget vulputate maximus, leo augue viverra elit, nec dapibus turpis felis id magna. Mauris dapibus eleifend ipsum, a tempor massa blandit ut</p>
              </div>
            </div>
          </div>
        </div>.panel-collapse
      </div>.panel

      <div class="panel panel-default">
        <a href="#first-day-3" class="panel-header" data-toggle="collapse" data-parent="#schedule-table-first-day">
          <div class="row">
            <div class="col-md-2 col-sm-2">
              <div class="time">
                <i class="fa fa-clock-o"></i>
                <figure>10:45</figure>
              </div>
            </div>
            <div class="col-md-10 col-sm-10">
              <div class="title"><h3>Coffee Break</h3></div>
            </div>
          </div>
          <i class="fa fa-plus"></i>
        </a>.panel-header
        <div id="first-day-3" class="panel-collapse collapse description">
          <div class="row">
            <div class="col-md-10 col-md-offset-2 col-sm-10 col-sm-offset-2">
              <div class="panel-body">
                <p>Nulla volutpat aliquam augue, et ullamcorper turpis porttitor a. Duis ac faucibus augue. Maecenas vel massa varius, rhoncus nibh id, sodales nisi.</p>
              </div>
            </div>
          </div>
        </div>.panel-collapse
      </div>.panel -->

    </div>
  </div><!-- .tab-pane -->
</div><!-- .tab-content -->

conference/templates/plugins/conference/speakers.html
{% load staticfiles %}
<section class="speakers background-stripe">
  {% for speakers in speakers_list %}
  <div class="row">
    {% for speaker in speakers %}
    <div class="col-md-3 col-sm-3">
      <div class="speaker">
        <aside class="image">
          <div class="plus-wrapper" data-toggle="modal" data-target="#modal{{ forloop.counter }}">
            <div class="plus"><i class="fa fa-plus"></i></div>
          </div>
          {% if speaker.picture %}
          <img src="{{ speaker.picture.url }}" alt="{{ speaker.name }}">
          {% else %}
          <img src="{% static 'img/speaker-01.png' %}" alt="">
          {% endif %}
        </aside>
        <h3>{{ speaker.name }}</h3>
        <h4>{{ speaker.reference }}</h4>
      </div><!-- .speaker -->
    </div><!-- .col-md-3 -->
    <div class="modal fade" id="modal{{ forloop.counter }}" tabindex="-1" role="dialog" aria-labelledby="modal1-label" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <div class="speaker-wrapper">
              <div class="speaker">
                <aside class="image">
                  {% if speaker.picture %}
                  <img src="{{ speaker.picture.url }}" alt="{{ speaker.name }}">
                  {% else %}
                  <img src="{% static 'img/speaker-01.png' %}" alt="">
                  {% endif %}
                </aside>
              </div><!-- .speaker -->
              <div class="speaker-name">
                <h1>{{ speaker.name }}</h1>
                <h2>{{ speaker.reference }}</h2>
              </div>
            </div>
          </div><!-- .modal-header -->
          <div class="modal-body">
            <div class="row">
              <div class="col-md-3 col-sm-3">
                <div class="social">
                  {% if speaker.facebook %}
                  <a href="{{ speaker.facebook }}">Facebook</a>
                  {% endif %}
                  {% if speaker.twitter %}
                  <a href="{{ speaker.twitter }}">Twitter</a>
                  {% endif %}
                  {% if speaker.googleplus %}
                  <a href="{{ speaker.googleplus }}">Google Plus</a>
                  {% endif %}
                  {% if speaker.homepage %}
                  <a href="{{ speaker.homepage }}">Homepage</a>
                  {% endif %}
                </div>
              </div>
              <div class="col-md-9 col-sm-9">
                <h3>About me</h3>
                {{ speaker.about|linebreaks }}
              </div>
            </div>
          </div><!-- .modal-body -->
          <div class="modal-footer">
            <div class="speak">
              {% for schedule in speaker.schedules %}
              <div class="row">
                <div class="col-md-8 col-sm-7">
                  <div class="title"><h3>{{ schedule.title }}</h3></div>
                </div>
                <div class="col-md-4 col-sm-5">
                  <div class="date-time">
                    <div class="date">
                      <i class="fa fa-calendar"></i>
                      <figure>{{ conference.realization_date }}</figure>
                    </div>
                    <div class="time">
                      <i class="fa fa-clock-o"></i>
                      <figure>{{ schedule.start_at }}</figure>
                    </div>
                  </div>
                </div>
              </div><!-- .row -->
              {% endfor %}
            </div><!-- .speak -->
          </div><!-- .modal-footer -->
        </div><!-- .modal-content -->
      </div><!-- .modal-dialog -->
    </div><!-- #modal1 -->
    {% endfor %}
  </div><!-- .row -->
  {% endfor %}
</section><!-- .speakers -->

core/templates/base.html
{% load cms_tags menu_tags sekizai_tags staticfiles %}
<!DOCTYPE html>
<html lang="en-US">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="author" content="ThemeStarz">
  <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.min.css' %}" type="text/css">
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}" type="text/css">
  <link rel="stylesheet" href="{% static 'css/bootstrap-select.min.css' %}" type="text/css">
  <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}" type="text/css">
  <link rel="stylesheet" href="{% static 'css/owl.transitions.css' %}" type="text/css">
  <link rel="stylesheet" href="{% static 'css/animate.css' %}" type="text/css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
  {% render_block "css" %}
  <title>{% page_attribute "page_title" %}</title>
</head>

<body data-spy="scroll" data-target=".navigation" data-offset="150" id="top">
  {% cms_toolbar %}
  <!-- Wrapper -->
  <div class="wrapper">

    <!-- Navigation -->
    <div class="navigation fade-in">
      <div class="container">
        <header class="navbar" role="banner" style="padding:15px 0;">
          <div class="navbar-header">
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <div class="navbar-brand nav" id="brand">
              <a href="#top"><img src="{% static 'img/uaipython-logo2.png' %}" alt="brand" style="height:80px;"></a>
            </div>
          </div>
          <div class="navigation-wrapper">
            <nav class="collapse navbar-collapse bs-navbar-collapse navbar-right" role="navigation">
              <ul class="nav navbar-nav">
                {% show_menu 0 1 100 100 "plugins/menu.html" %}
              </ul>
            </nav><!-- /.navbar collapse-->
          </div>
        </header><!-- /.navbar -->
      </div><!-- /.container -->
    </div>
    <!-- end Navigation -->

    <!-- Slider -->
    <div class="slider">
      <div class="overlay">
        <div class="container">
          <div class="information fade-in move">
            <div><i class="fa fa-map-marker"></i>{{ conference.address }}</div>
            <div><i class="fa fa-calendar"></i>{{ conference.realization_at|date:"d/m/Y" }}</div>
          </div>
          <div class="title-wrapper fade-in">
            <div class="title expand move"><h1>{{ conference.site.name }}</h1></div>
            <div class="title expand move"><h1>Conferência</h1></div>
          </div>
          <div class="call-to-action fade-in move" style="display: none;">
            <a href="#register" class="roll">Register!</a>
          </div>
        </div>
      </div>
      {% static_placeholder "banner" %}
      <!-- <div id="slider" class="owl-carousel has-parallax">
        <div class="slide">
          <img src="{% static 'img/slide.jpg' %}" alt="">
        </div>
        <div class="slide">
          <img src="{% static 'img/slide-02.jpg' %}" alt="">
        </div>
      </div> -->
    </div>
    <!-- end Slider -->

    <!-- Page Content -->
    <div id="page-content">
      {% placeholder "base_content" %}
    </div>
    <!-- end Page Content -->

    <!-- Footer -->
    <footer id="contact">
      <section class="footer-top">
        <div class="container">
          <header>
            <h2><a href="#contact" class="roll">Contato & Localização</a></h2>
          </header>
          <div class="find-way">
            <div class="row">
              <div class="col-md-5 col-sm-7 col-md-offset-7 col-sm-offset-5">
                <div class="form-group">
                  <div class="input-group">
                    <div class="input-group-addon"><i class="fa fa-map-marker"></i></div>
                    <input type="text" class="form-control" id="find-way" name="find-way" placeholder="Digite sua localização para obter o caminho">
                  </div>
                </div><!-- /.form-group -->
              </div><!-- .col-md-5 -->
            </div><!-- .row -->
          </div><!-- .find-way -->
        </div><!-- .container -->
      </section>
      <div id="map"></div><!-- #map -->
      <section class="footer-bottom">
        <div class="container">
          <div class="row">
            <div class="col-md-7 col-sm-6">
              <section class="copyright">
                <span>Copyright © <a href="#">UAI Python</a>, 2015</span>
              </section>
            </div><!-- .col-md-7 -->
            <div class="col-md-5 col-sm-6">
              <section class="contact float">
                <h3>Fique conectado!</h3>
                <div class="social">
                  <a href="https://www.facebook.com/uaipython/">Facebook</a>
                  <a href="https://twitter.com/pythonmg/">Twitter</a>
                  <a href="http://forum.pythonmg.com.br/">Groups</a>
                  <a href="http://pythonmg.com.br/">PUG</a>
                </div>
                <span>Entre em contato <a href="mailto:contato@uaipython.org">contato@uaipython.org</a></span>
              </section>
            </div><!-- .col-md-5 -->
          </div><!-- .row -->
        </div><!-- .container -->
      </section>
      <!-- .footer-bottom -->
    </footer>
    <!-- end Footer -->

  </div>
  <!-- end Wrapper -->

  <script type="text/javascript" src="{% static 'js/jquery-2.1.3.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/jquery-migrate-1.2.1.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/smoothscroll.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/owl.carousel.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/bootstrap-select.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/jquery.validate.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/jquery.placeholder.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/icheck.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/jquery.eachStep.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/jquery.fitvids.js' %}"></script>
  <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false&libraries=places"></script>
  <script type="text/javascript" src="{% static 'js/markerwithlabel_packed.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/retina-1.1.0.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/custom.js' %}"></script>

  <!-- Google Maps -->
  <script type="text/javascript">
    var _latitude = parseFloat("{{ conference.latitude }}");
    var _longitude = parseFloat("{{ conference.longitude }}");
    var markerAddress = "{{ conference.address }}";
    var mapStyles = [{featureType:'water',elementType:'all',stylers:[{hue:'#d7ebef'},{saturation:-5},{lightness:54},{visibility:'on'}]},{featureType:'landscape',elementType:'all',stylers:[{hue:'#eceae6'},{saturation:-49},{lightness:22},{visibility:'on'}]},{featureType:'poi.park',elementType:'all',stylers:[{hue:'#dddbd7'},{saturation:-81},{lightness:34},{visibility:'on'}]},{featureType:'poi.medical',elementType:'all',stylers:[{hue:'#dddbd7'},{saturation:-80},{lightness:-2},{visibility:'on'}]},{featureType:'poi.school',elementType:'all',stylers:[{hue:'#c8c6c3'},{saturation:-91},{lightness:-7},{visibility:'on'}]},{featureType:'landscape.natural',elementType:'all',stylers:[{hue:'#c8c6c3'},{saturation:-71},{lightness:-18},{visibility:'on'}]},{featureType:'road.highway',elementType:'all',stylers:[{hue:'#dddbd7'},{saturation:-92},{lightness:60},{visibility:'on'}]},{featureType:'poi',elementType:'all',stylers:[{hue:'#dddbd7'},{saturation:-81},{lightness:34},{visibility:'on'}]},{featureType:'road.arterial',elementType:'all',stylers:[{hue:'#dddbd7'},{saturation:-92},{lightness:37},{visibility:'on'}]},{featureType:'transit',elementType:'geometry',stylers:[{hue:'#c8c6c3'},{saturation:4},{lightness:10},{visibility:'on'}]}];

    google.maps.event.addDomListener(window, 'load', initSubmitMap());

    function initSubmitMap(){
      var mapCenter = new google.maps.LatLng(_latitude,_longitude);
      var mapOptions = {
        zoom: 15,
        center: mapCenter,
        disableDefaultUI: false,
        scrollwheel: false,
        styles: mapStyles
      };
      var mapElement = document.getElementById('map');
      var map = new google.maps.Map(mapElement, mapOptions);

      var markerPosition = new google.maps.LatLng(_latitude,_longitude);
      var marker = new MarkerWithLabel({
        position: markerPosition,
        map: map,
        icon: "{% static 'img/marker.png' %}",
        labelContent: markerAddress,
        labelAnchor: new google.maps.Point(50, 0),
        labelClass: "marker-style"
      });


      var input = /** @type {HTMLInputElement} */( document.getElementById('find-way') );
      var autocomplete = new google.maps.places.Autocomplete(input);
      autocomplete.bindTo('bounds', map);
      google.maps.event.addListener(autocomplete, 'place_changed', function() {
        var place = autocomplete.getPlace();
        if (!place.geometry) {
          return;
        }
        if (place.geometry.viewport) {
          map.fitBounds(place.geometry.viewport);
        } else {
          map.setCenter(place.geometry.location);
          map.setZoom(17);
        }
        marker.setPosition(place.geometry.location);
        marker.setVisible(true);

        initialize(place.geometry.location.lat(), place.geometry.location.lng());

        var address = '';
        if (place.address_components) {
          address = [
          (place.address_components[0] && place.address_components[0].short_name || ''),
          (place.address_components[1] && place.address_components[1].short_name || ''),
          (place.address_components[2] && place.address_components[2].short_name || '')
          ].join(' ');
        }
      });


      var directionsDisplay;
      var directionsService = new google.maps.DirectionsService();
      var finishPoint = new google.maps.LatLng(_latitude, _longitude);

      function initialize(_findLatitude, _findLongitude) {
            //alert(center);
            var startPoint = new google.maps.LatLng(_findLatitude, _findLongitude);
            directionsDisplay = new google.maps.DirectionsRenderer();
            var mapOptions = {
              zoom: 14,
              center: startPoint,
              scrollwheel: true,
              styles: mapStyles
            };
            map = new google.maps.Map(document.getElementById('map'), mapOptions);
            directionsDisplay.setMap(map);

            var selectedMode = 'DRIVING';
            var request = {
              origin: startPoint,
              destination: finishPoint,
              travelMode: google.maps.TravelMode[selectedMode]
            };
            directionsService.route(request, function(response, status) {
              if (status == google.maps.DirectionsStatus.OK) {
                directionsDisplay.setDirections(response);
              }
            });


          }
        }

      </script>
      {% render_block "js" %}
    </body>
    </html>

core/templates/plugins/about.html
<section class="about">
  <div class="row">
    <div class="col-md-6 col-sm-12">
      <div class="information">
        <div class="date">
          <div class="day">{{ conference.realization_at|date:'d' }}</div>
          <div class="divider">/</div>
          <div class="month">{{ conference.realization_at|date:'m' }}</div>
          <div class="divider">/</div>
          <div class="year">{{ conference.realization_at|date:'Y' }}</div>
        </div>
        <div class="location">{{ conference.get_city_display }}</div>
        <div class="address">{{ conference.address }}</div>
      </div><!-- .information -->
      <hr>
      {{ instance.body|linebreaks }}
    </div>
    <div class="col-md-6 col-sm-12">
      <div class="video">
        {{ instance.media|safe }}
      </div><!-- .video -->
    </div><!-- .col-md-6 -->
  </div><!-- .row -->
</section><!-- .about -->

core/templates/plugins/anchor.html
<header>
  <h2><a href="#{{ instance.identify }}" class="roll">{{ instance.name }}</a></h2>
</header>

core/templates/plugins/menu.html
{% for child in children %}
  <li><a href="{{ child.attr.redirect_url|default:child.get_absolute_url }}" class="fade-in">{{ child.get_menu_title }}</a></li>
{% endfor %}

core/templates/plugins/page_content.html
{% load cms_tags %}
<section class="block{% if instance.background %} background-color-grey-light{% endif %}" id="{{ instance.identify }}"{% if 'edit' not in request.GET.keys and not instance.published %}style="display:none;"{% endif %}>
  <div class="container">
  {% for plugin in instance.child_plugin_instances %}
    {% render_plugin plugin %}
  {% endfor %}
  </div>
</section>

core/templates/plugins/page_footer.html
<section class="footer-top">
  <div class="container">
    <header>
      <h2><a href="#contact" class="roll">Contact & Location</a></h2>
    </header>
    <div class="find-way">
      <div class="row">
        <div class="col-md-5 col-sm-7 col-md-offset-7 col-sm-offset-5">
          <div class="form-group">
            <div class="input-group">
              <div class="input-group-addon"><i class="fa fa-map-marker"></i></div>
              <input type="text" class="form-control" id="find-way" name="find-way" placeholder="Enter your location to find a way">
            </div>
          </div><!-- /.form-group -->
        </div><!-- .col-md-5 -->
      </div><!-- .row -->
    </div><!-- .find-way -->
  </div><!-- .container -->
</section>
<div id="map"></div><!-- #map -->
<section class="footer-bottom">
  <div class="container">
    <div class="row">
      <div class="col-md-7 col-sm-6">
        <section class="copyright">
          <span>Copyright © <a href="#">EVENT ˣ</a> , 2014</span>
        </section>
      </div><!-- .col-md-7 -->
      <div class="col-md-5 col-sm-6">
        <section class="contact float">
          <h3>Get Connected</h3>
          <div class="social">
            <a href="#">Facebook</a>
            <a href="#">Twitter</a>
            <a href="#">YouTube</a>
          </div>
          <span>Reach us at <a href="mailto:eventx@example.com">eventx@example.com</a> for any questions</span>
        </section>
      </div><!-- .col-md-5 -->
    </div><!-- .row -->
  </div><!-- .container -->
</section>

core/templates/plugins/slides.html
{% load staticfiles %}
<div id="slider" class="owl-carousel has-parallax">
  {% for slide in instance.slide_set.all %}
  <div class="slide">
    {% if slide.image %}
    <img src="{{ slide.image.url }}" alt="{{ slide.title }}">
    {% else %}
    <img src="{% static 'img/slide.jpg' %}" alt="">
    {% endif %}
  </div>
  {% endfor %}
  <!-- <div class="slide">
    <img src="{% static 'img/slide-02.jpg' %}" alt="">
  </div> -->
</div>